django/professors/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'professors'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('manage_courses_and_projects/', views.manage_courses_and_projects, name='manage_courses_and_projects'),
    path('manage_courses_and_projects/<str:tab>/', views.manage_courses_and_projects_tab, name='manage_courses_and_projects'),
    path('manage_courses_and_projects/<str:tab>/<str:section>/', views.manage_courses_and_projects_tab_section, name='manage_courses_and_projects'),

    path('create_course/', views.create_course, name='create_course'),
    path('edit_course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('confirm_delete_course/<int:course_id>/', views.confirm_delete_course, name='confirm_delete_course'),
    path('delete_course/<int:course_id>/', views.delete_course, name='delete_course'),

    path('create_project/', views.create_project, name='create_project'),
    path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
    path('confirm_delete_project/<int:project_id>/', views.confirm_delete_project, name='confirm_delete_project'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('add_section/<int:course_id>/<int:project_id>/', views.add_section, name='add_section'),
    path('confirm_remove_section/<int:section_id>/<int:project_id>/', views.confirm_remove_section, name='confirm_remove_section'),
    path('remove_section/<int:section_id>/<int:project_id>/', views.remove_section, name='remove_section'),

    path('create_section/', views.create_section, name='create_section'),
    path('edit_section/<int:section_id>/', views.edit_section, name='edit_section'),
    path('confirm_delete_section/<int:section_id>/', views.confirm_delete_section, name='confirm_delete_section'),
    path('delete_section/<int:section_id>/', views.delete_section, name='delete_section'),

    path('add_students/<int:institution_id>/<int:section_id>/<str:redirect_tab>/',
        views.add_students, name='add_students'
    ),
    #path('debug/', views.debug, name='debug')
]

django/projectconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public_pages.urls')),
    path('professors/', include('professors.urls')),
    path('students/', include('students.urls')),
    path('users/', include('users.urls')),
]

django/public_pages/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as users_views
from . import views

app_name = 'public_pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('about/<str:section>', views.about_section, name='about_section'),
    path('hotjar/', views.hotjar, name='hotjar'),
    # In addition to users/login being valid URL, I'm
    # making login and accounts/login valid URLs for the
    # login page too.
    path('accounts/login/', users_views.login_view, name='login'),
    path('login/', users_views.login_view, name='login'),
]


handler404 = views.handle_404

django/users/urls.py
from django.urls import path, reverse_lazy
from django.urls import path, include
from django.contrib.auth import login, views as auth_views
from . import views
from .forms import CustomSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('choose_app_view/', views.choose_app_view, name='choose_app_view'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('route_user/', views.route_user, name='route_user'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/password_reset/reset_password_email.html',
			email_template_name='users/password_reset/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_sent'),
		), name='reset_password'),

	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/password_reset/reset_password_sent.html'), name='password_reset_sent'),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            form_class=CustomSetPasswordForm,
			template_name='users/password_reset/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='password_reset_confirm'),

	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/password_reset/reset_password_complete.html'), name='password_reset_complete')
]

django/professors/models.py
from pyexpat import model
from django.db import models
from institutions.models import Institution
from users.models import EmailAuthUser
from students.models import Student

from functools import partial
from os import path


def _update_filename(instance, filename, path):
    return path.join(path, filename)

def upload_to(path):
    return partial(_update_filename, path=path)


class S3Upload(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)


class S3ProfessorUpload(S3Upload):
    _upload_to='img/professors/profile_icons'
    file = models.FileField(upload_to=(_upload_to))


class Professor(models.Model):
    title        = models.CharField(max_length=100)
    pronouns     = models.CharField(max_length=100)
    suffix       = models.CharField(max_length=10)
    bio          = models.CharField(max_length=300)

    profile_icon           = models.FileField()
    profile_icon_file_name = models.CharField(max_length=30, default='default_profile_icon.png')

    institution = models.ForeignKey(Institution, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(EmailAuthUser, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"\nid:         {self.id}\n"
            f"title:       {self.title}\n"
            f"institution: {self.institution}\n"
            f"profile icon path:      '{S3ProfessorUpload._upload_to}'\n"
            f"profile icon file name: '{self.profile_icon_file_name}'"
        )

    def print_userfriendly(self):
        return(
            f"{self.user.last_name}\n"
        )


class Course(models.Model):
    code = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"\n{self.code}: {self.description}"
            f", {self.professor.user.last_name}"
        )


class Project(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"\ntitle:      {self.title}\n"
            f"description: {self.description}\n"
            f"course:      {self.course.code}\n"
        )


class Section(models.Model):
    section_code = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    projects = models.ManyToManyField(Project)
    students = models.ManyToManyField(Student)
    
        

    



django/professors/views.py
from xml.etree.ElementInclude import include
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from professors.forms import *
from users.decorators import allowed_users
from professors.models import *
from students.models import Student
from datetime import datetime as dt, timedelta
from django.views.decorators.cache import never_cache
from django.contrib import messages
import json
from os import path


@login_required
@allowed_users(allowed_groups=['professors'])
def index(request):
    professor = Professor.objects.get(user=request.user)

    context = {
        'courses' : Course.objects.filter(professor=professor),
    }
    return render(request, 'professors/index.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def debug(request):
    courses = Course.objects.all()
    projects = Project.objects.all()
    sections = Section.objects.all()
    students = Student.objects.all()
    context = {
        'courses': courses,
        'projects': projects,
        'sections': sections,
        'students': students
    }
    return render(request, 'professors/debug.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def edit_profile(request):
    professor = Professor.objects.get(user=request.user) 
    if request.method != 'POST': 
        form = ProfessorForm(instance=professor)
    else:                                       
        form = ProfessorForm(instance=professor, data=request.POST) 
        if form.is_valid():
            form.save()
            if len(request.FILES) != 0:
                if 'profile_icon' in request.FILES.keys():
                    image = request.FILES['profile_icon']
                    image.name = 'profile-icon-' + str(professor.id) + path.splitext(image.name)[1]
                    u = S3ProfessorUpload(file=image)
                    u.save()
                    professor.profile_icon_file_name=image.name
                    professor.save()

            return HttpResponseRedirect(reverse('professors:manage_courses_and_projects'))

    context = { 'professor': professor, 'form': form }
    return render(request, 'professors/edit_profile_form.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def manage_courses_and_projects(request):
    professor = Professor.objects.get(user=request.user)
    courses = Course.objects.filter(professor=professor)

    context = {
        'courses': courses,
        'goto_tab': 'courses'
    }
    return render(request, 'professors/manage_courses_and_projects.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def manage_courses_and_projects_tab(request, tab):
    professor = Professor.objects.get(user=request.user)
    courses = Course.objects.filter(professor=professor)

    context = {
        'courses': courses,
        'goto_tab': tab
    }
    return render(request, 'professors/manage_courses_and_projects.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def manage_courses_and_projects_tab_section(request, tab, section):
    professor = Professor.objects.get(user=request.user)
    courses = Course.objects.filter(professor=professor)

    context = {
        'courses': courses,
        'goto_tab': tab,
        'goto_section': section
    }
    return render(request, 'professors/manage_courses_and_projects.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def create_course(request): 
    professor = Professor.objects.get(user=request.user) #get the current professor
    course = Course(professor=professor) #create a course and specify that the professor value of the course will be set = to the professor

    if request.method != 'POST':
        form = CourseForm(instance=course)  #Create the form instance of the course
    else:
        form = CourseForm(instance=course, data=request.POST) #Create the form, instance of the course with a DR post
        if len(request.POST['course_sections']) == 0:
            form.add_error('course_sections', 'You must create at least one section')

        if form.is_valid():
            form.save() #If the form is valid, save it.
            sections_str = request.POST['course_sections'].split(';')
            for sc in sections_str: # Build the sections
                if not sc == '':
                    section = Section(
                        section_code=sc,
                        description='',
                        course=course
                    )
                    section.save()
            return HttpResponseRedirect(reverse('professors:manage_courses_and_projects'))

    context = { 'form': form }
    return render(request, 'professors/create_course_form.html', context)


@login_required
@allowed_users(allowed_groups=['professors'])
def edit_course(request, course_id):
    course = Course.objects.get(id=course_id)
    sections = Section.objects.filter(course=course)

    section_ids_str = ""
    section_codes_str = ""

    for section in sections:
        section_ids_str += str(section.id) + ";"
        section_codes_str += section.section_code + ";"

    section_ids_str.rstrip(';')
    section_codes_str.rstrip(';')

    if request.method != 'POST':
        form = CourseForm(instance=course)  #Create the form instance of the course
    else:
        form = CourseForm(instance=course, data=request.POST) #Create the form, instance of the course with a DR post
        if ( (len(request.POST['course_sections']) == 0)
                and (len(request.POST['course_sections_to_delete']) >= len(sections)) ):
            form.add_error('course_sections', 'You must create at least one section')

        elif form.is_valid():
            form.save() #If the form is valid, save it.
            sections_str = request.POST['course_sections_to_delete'].split(';')
            for s_id in sections_str:
                if not s_id == '':
                    section = Section.objects.get(id=int(s_id))
                    section.delete()

            sections_str = request.POST['course_sections'].split(';')
            for sc in sections_str: # Build the sections
                if not sc == '':
                    section = Section(
                        section_code=sc,
                        description='',
                        course=course
                    )
                    section.save()
            return HttpResponseRedirect(reverse('professors:manage_courses_and_projects', args=['projects']))

    context = {
        'form': form,
        'course': course,
        'created_course_sections': section_codes_str,
        'created_course_section_ids': section_ids_str
    }

    return render(request, 'professors/edit_course_form.html', context)

@never_cache
@login_required
def add_students(request, institution_id, section_id, redirect_tab):
    institution = Institution.objects.get(id=institution_id)
    institution_students = Student.objects.filter(institution=institution)
    section = Section.objects.get(id=section_id)
    section_students = section.students.all()
    section_students_ids = section_students._clone().values_list('id', flat=True)

    if request.method == 'POST':
        students = request.POST['add_students'].split(';')

        for id_str in students:
            id = int(id_str)
            s = Student.objects.get(id=id)
            if not id in section_students_ids:
                try:
                    section.students.add(s)
                except Exception as e:
                    print(e)

        students = request.POST['remove_students'].split(';')

        for id_str in students:
            id = int(id_str)
            s = Student.objects.get(id=id)
            try:
                section.students.remove(s)
            except:
                pass

        return HttpResponseRedirect(reverse('professors:manage_courses_and_projects', args=[redirect_tab]))

    if redirect_tab == 'home':
        redirect_url = "/professors/"
    else:
        redirect_url = f"/professors/manage_courses_and_projects/{redirect_tab}/"

    context = {
        'submit_url': f"/professors/add_students/{institution_id}/{section_id}/{redirect_tab}/",
        'redirect_url': redirect_url,
        'institution_id': institution.id,
        'section_id': section.id,
        'redirect_tab': redirect_tab,
        'students': institution_students,
        'existing_students': section_students,
    }

    return render(request, 'professors/add_students_form.html', context)

@never_cache
@login_required
def add_section(request, course_id, project_id):
    course = Course.objects.get(id=course_id)
    project = Project.objects.get(id=project_id)

    if request.method != 'POST':
        form = AddSectionForm(course=course)
    else:
        form = AddSectionForm(course=course, data=request.POST)
        if form.is_valid():
            section_code = form.data['section_choice']

            try:
                sections = Section.objects.filter(course=course)
                section = sections.get(section_code=section_code)
                section.projects.add(project)
                section.save()
                print(section.projects.all())
            except Exception as e:
                print(e)
                pass

            return HttpResponseRedirect(reverse('professors:manage_courses_and_projects', args=['projects']))

    context = {
        'form': form,
        'course_id': course.id,
        'project_id': project.id
    }
    return render(request, 'professors/add_section.html', context)


django/templates/professors/add_section.html
{% extends './base.html' %}

{% block title %}Assign a Section{% endblock title %}

{% block more_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock more_links %}

{% block content %}
{% load crispy_forms_tags %}
<br>
<div class="container-sm flow">
	<div class="lightly-pad-container shadow text-break text-center border-dotted-brand-green">
		<div class="text-center title"><h2>Assign Project to Section</h2></div>
		<div class="form-container">
			<form action="{% url 'professors:add_section' course_id project_id %}" method='post'>
				{% crispy form %}
				<div class="form-row">
                    <div class="col-25">
                        &nbsp;
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button onclick="javascript:history.back();" class="btn btn-danger">Cancel</button>
                    </div>
                </div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

django/templates/professors/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <title>PC Professor - {% block page_title %}{% endblock page_title %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="student, professor, rate, team, project, review, peer, group">
    <meta name="author" content="ProjectConnect">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index follow">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&family=Bellefair&family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    {% block more_links %}
    {% endblock more_links %}

    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

    {{ hotjar_script|safe }}

    <style>
        #navbar-brand { white-space: nowrap; }
        .navbar-img { display: inline-block; }
        {% block page_style %}{% endblock page_style %}
    </style>
</head>

<body class="bg-white">
    <div class="page-container">
        <div class="content-wrap">
            <nav class="navbar navbar-expand-lg navbar-light bg-white shadow"
                style="border-top: 1px solid hsl( var(--clr-brand-blue) ); border-bottom: 3px solid hsl( var(--clr-brand-blue) );">
                <div class="navbar-brand">
                    <a href="{% url 'professors:index' %}"><img class="navbar-img" src="{% static 'img/projectconnect-logo-lg.png' %}"
                        alt="ProjectConnect logo featuring prominent C-shape with user icons" width="10%" style="margin-right: 1rem;"></a>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive"
                    aria-expanded="false", aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto" style="text-align: center;">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'professors:index' %}" alt="Link to homepage">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                                </svg>
                                <br>Home<span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'professors:manage_courses_and_projects' tab='courses' %}" alt="Link to Manage Courses">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
                                    <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
                                    <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"/>
                                  </svg>
                                <br>Courses
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'professors:manage_courses_and_projects' tab='projects' %}" alt="Link to Manage Projects">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-archive-fill" viewBox="0 0 16 16">
                                    <path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                                </svg>
                                <br>Projects
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-dropbttn" onclick="toggleDropdown('profile-dropdown-content')" alt="Link to profile page">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                </svg>
                                <br>Profile
                            </a>
                            <div class="profile-dropdown-content nav-dropdown-content" id="profile-dropdown-content">
                                <div class="row card-row">
                                    <div class="col">
                                        {% with 'img/professors/profile_icons/'|add:professor.profile_icon_file_name as profile_icon_static %}
                                        <img class="border-brand-blue" style="border-radius: 50%;"
                                            src="{% static profile_icon_static %}" alt="Profile icon">
                                        {% endwith %}
                                    </div>
                                    <div class="col">
                                        {{ user.first_name }} {{ user.last_name }}
                                        {% if not professor.suffix == '' %}
                                        , {{ professor.suffix }}
                                        {% endif %}
                                    </div>
                                </div>
                                <a href="{% url 'professors:edit_profile' %}">Edit profile</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-dropbttn" onclick="toggleDropdown('settings-dropdown-content')" alt="Link to open Settings menu">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                                </svg>
                                <br>Settings
                            </a>
                            <div class="nav-dropdown-content" id="settings-dropdown-content">
                                <div class="row card-row">
                                    <div class="col fs-300 text-dark"><a href="{% url 'users:logout' %}">Log out</a></div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <footer class="shadow text-right">
        <div>
            <a class="bttn-outline-brand-blue" href="{% url 'public_pages:about' %}" alt="Link to About Us page" style="float: left; margin-top: 1em;">About Us</a>
            <span class="fs-100 text-right"><a href="#" style="text-decoration: none; color: #000;"> &copy;</a>
                &nbsp;ProjectConnect, Inc. 2022</span>
        </div>
        <div>
            <img class="navbar-img" id="hide-on-small-phone" src="{% static 'img/projectconnect-logo-footer.png' %}"
                alt="ProjectConnect logo featuring prominent C-shape with user icons" style="float: right;">
        </div>
    </footer>

    <script>
        function closeDropdowns() {
            let dropdowns = document.getElementsByClassName("nav-dropdown-content");
            let i;
            for (i = 0; i < dropdowns.length; i++) {
              let openDropdown = dropdowns[i];
              console.log(i);
              if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
              }
            }
        }

        function toggleDropdown(id) {
            closeDropdowns(); // First close dropdowns that could already be open.
            document.getElementById(id).classList.toggle("show");
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.nav-dropbttn')) {
                closeDropdowns();
            }
        }
    </script>
    {% block body_scripts %}{% endblock body_scripts %}
</body>

</html>

django/templates/professors/confirm_delete_item.html
{% extends './base.html' %}
{% block page_title %}Delete {{ item_name }} {% endblock page_title %}

{% block more_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock more_links %}

{% block content %}
<br>
<div class="container-sm flow">
	<div class="lightly-pad-container shadow text-break text-center">
		<h2 class="ff-sans-bolder">Delete {{ item_name }}</h2>
		<div class="form-container">
			<div>
				<p>
					Deleting this {{ item_name }} {{ item_description }}
					cannot be undone. Are you sure you want to delete?
				</p>
				<div class="form-row center">
					<div class="col-25" style="text-align: left;">
					</div>
					<div class="col-25" style="text-align: left;">
						<button class="bttn-brand-blue" onclick="javascript:history.back();">Cancel</button>
					</div>
					<div class="col-25" style="text-align: left;">
						<a href="{% url item_delete_url item_id %}"><button class="bttn-danger">Delete</button></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}