django/professors/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'professors'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('manage_courses_and_projects/', views.manage_courses_and_projects, name='manage_courses_and_projects'),
    path('manage_courses_and_projects/<str:tab>/', views.manage_courses_and_projects_tab, name='manage_courses_and_projects'),
    path('manage_courses_and_projects/<str:tab>/<str:section>/', views.manage_courses_and_projects_tab_section, name='manage_courses_and_projects'),

    path('create_course/', views.create_course, name='create_course'),
    path('edit_course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('confirm_delete_course/<int:course_id>/', views.confirm_delete_course, name='confirm_delete_course'),
    path('delete_course/<int:course_id>/', views.delete_course, name='delete_course'),

    path('create_project/', views.create_project, name='create_project'),
    path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
    path('confirm_delete_project/<int:project_id>/', views.confirm_delete_project, name='confirm_delete_project'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('add_section/<int:course_id>/<int:project_id>/', views.add_section, name='add_section'),
    path('confirm_remove_section/<int:section_id>/<int:project_id>/', views.confirm_remove_section, name='confirm_remove_section'),
    path('remove_section/<int:section_id>/<int:project_id>/', views.remove_section, name='remove_section'),

    path('create_section/', views.create_section, name='create_section'),
    path('edit_section/<int:section_id>/', views.edit_section, name='edit_section'),
    path('confirm_delete_section/<int:section_id>/', views.confirm_delete_section, name='confirm_delete_section'),
    path('delete_section/<int:section_id>/', views.delete_section, name='delete_section'),

    path('add_students/<int:institution_id>/<int:section_id>/<str:redirect_tab>/',
        views.add_students, name='add_students'
    ),
    #path('debug/', views.debug, name='debug')
]

django/projectconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public_pages.urls')),
    path('professors/', include('professors.urls')),
    path('students/', include('students.urls')),
    path('users/', include('users.urls')),
]

django/public_pages/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as users_views
from . import views

app_name = 'public_pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('about/<str:section>', views.about_section, name='about_section'),
    path('hotjar/', views.hotjar, name='hotjar'),
    # In addition to users/login being valid URL, I'm
    # making login and accounts/login valid URLs for the
    # login page too.
    path('accounts/login/', users_views.login_view, name='login'),
    path('login/', users_views.login_view, name='login'),
]


handler404 = views.handle_404

django/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

django/users/urls.py
from django.urls import path, reverse_lazy
from django.urls import path, include
from django.contrib.auth import login, views as auth_views
from . import views
from .forms import CustomSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('choose_app_view/', views.choose_app_view, name='choose_app_view'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('route_user/', views.route_user, name='route_user'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/password_reset/reset_password_email.html',
			email_template_name='users/password_reset/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_sent'),
		), name='reset_password'),

	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/password_reset/reset_password_sent.html'), name='password_reset_sent'),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            form_class=CustomSetPasswordForm,
			template_name='users/password_reset/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='password_reset_confirm'),

	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/password_reset/reset_password_complete.html'), name='password_reset_complete')
]

django/users/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Column
from password_validator import PasswordValidator
from django.contrib.auth.forms import SetPasswordForm

schema1 = PasswordValidator()
schema2 = PasswordValidator()

schema1\
.min(8)\
.max(100)\
.has().uppercase()\
.has().lowercase()\

schema1\
.has().digits()\
.has().no().spaces()


APP_ROLES = (
    ('students', 'Student'),
    ('professors', 'Professor'),
    ('both', 'Both')
)

#region Create an EmailAuthUser
class EmailAuthUserCreationForm(forms.Form):
    first_name = forms.CharField(
        label='First name',
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Your first name..',
        })
    )

    last_name = forms.CharField(
        label='Last name',
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Your last name..',
        })
    )

    email = forms.EmailField(
        label='School email',
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Your college/university email address..',
        })
    )

    password = forms.CharField(
        label='Create password',
        required=True,
        help_text='Must be 8-100 characters including an uppercase and lowercase character and a digit',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter password..',
        })
    )

    password_confirm = forms.CharField(
        label='Re-enter password',
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat the password..'
        })
    )

    role_choice = forms.CharField(
        label='Choose role',
        required=True,
        widget=forms.Select(choices=APP_ROLES)
    )

    tos = forms.BooleanField(
        label='Terms of Service',
        required=True,
    )

    def clean_email(self):
        if EmailAuthUser.objects.filter(email=self.cleaned_data['email'].lower()).exists():
            self.add_error('email', 'An account with this email address already exists.')

    def clean_password_confirm(self):
        passwd1 = self.cleaned_data['password']
        passwd2 = self.cleaned_data['password_confirm']

        if passwd1 and passwd2:
            # Check that passwords match
            if passwd1 != passwd2:
                self.add_error('password_confirm', 'The passwords do not match.')

            # Check password requirements
            if len(passwd1) < 8:
                self.add_error('password', "Password must be 8-100 characters")
            if not schema1.validate(passwd1):
                self.add_error('password', "Password must have an uppercase and a lowercase letter")
            if not schema2.validate(passwd1):
                self.add_error('password' "Password must contain a digit and no spaces")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-25 fs-400 ff-sans-normal'
        self.helper.field_class='col-75'
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('first_name')
            ),
            Row(
                Column('last_name')
            ),
            Row(
                Column('email')
            ),
            Row(
                Column('password')
            ),
            Row(
                Column('password_confirm')
            ),
            Row(
                Column('role_choice')
            )
        )
#endregion

class LoginForm(forms.Form):
    username = forms.EmailField(
        label='Email',
        required=True
    )

    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput()
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-25 fs-400 ff-sans-normal'
        self.helper.field_class='col-75'
        self.helper.form_tag = False

class CustomSetPasswordForm(SetPasswordForm):
    def clean_new_password2(self):
        print(self.cleaned_data.keys())
        passwd1 = self.cleaned_data['new_password1']
        passwd2 = self.cleaned_data['new_password2']

        if passwd1 and passwd2:
            # Check that passwords match
            if passwd1 != passwd2:
                self.add_error('new_password2', 'The passwords do not match.')

            # Check password requirements
            if len(passwd1) < 8:
                self.add_error('new_password1', "Password must be 8-100 characters")
            if not schema1.validate(passwd1):
                self.add_error('new_password1', "Password must have an uppercase and a lowercase letter")
            if not schema2.validate(passwd1):
                self.add_error('new_password1', "Password must contain a digit and no spaces")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-25 fs-400 ff-sans-normal'
        self.helper.field_class='col-75'
        self.helper.form_tag = False

django/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from institutions.models import Institution
from professors.models import Professor
from students.models import Student
from .forms import *

User = get_user_model()

#region Route the user depending on if theyre a professor or a student
@login_required
def route_user(request):
    if request.user.groups.exists():
        is_professor = False; is_student = False
        for group in request.user.groups.all():
            if group.name == 'professors':
                is_professor = True
            if group.name == 'students':
                is_student = True

        if is_professor and is_student:
            return HttpResponseRedirect(reverse('users:choose_app_view'))
        elif is_student:
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return HttpResponseRedirect(reverse('professors:index'))
    else:
        return HttpResponseRedirect(reverse('public_pages:index'))
#endregion

#region login_view
def login_view(request):
    logout(request)
    if request.method != 'POST':
        form = LoginForm()
    else:
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST['username'],
                                password=request.POST['password'])

            if not (user is None):
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('users:route_user'))
            else:
                messages.error(request, 'Email or password not correct')
                return redirect('users:login')

    context = { 'form': form }
    return render(request, 'users/login.html', context)

#region logout view
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('public_pages:index'))
#endregion

#region Register Form
def register(request):
    if request.method != 'POST':
        form = EmailAuthUserCreationForm()
    else:
        form = EmailAuthUserCreationForm(data=request.POST)
        formdata = request.POST

        if form.is_valid():
            email_domain = formdata['email'].split('@')[1]
            institutions = Institution.objects.filter(student_email_domain=email_domain)
            if len(institutions) == 0:
                institutions = Institution.objects.filter(professor_email_domain=email_domain)

            if len(institutions) == 1:
                user = User.objects.create_user(email=formdata['email'], password=formdata['password'])
                user.first_name=formdata['first_name']
                user.last_name=formdata['last_name']

                role_choice = formdata['role_choice']
                professors_group = Group.objects.get(name='professors')
                students_group = Group.objects.get(name='students')

                print(role_choice)

                if role_choice == 'both':
                    user.groups.add(professors_group)
                    user.groups.add(students_group)
                    prof = Professor(
                        title='',
                        pronouns='',
                        suffix='',
                        bio='',
                        institution=institutions[0],
                        user=user
                    )
                    prof.save()

                    student = Student(
                        pronouns='',
                        bio='',
                        institution=institutions[0],
                        user=user
                    )
                    student.save()

                elif role_choice == 'students':
                    user.groups.add(students_group)
                    student = Student(
                        pronouns='',
                        bio='',
                        institution=institutions[0],
                        user=user
                    )
                    student.save()
                else:
                    user.groups.add(professors_group)
                    prof = Professor(
                        title='',
                        pronouns='',
                        suffix='',
                        bio='',
                        institution=institutions[0],
                        user=user
                    )
                    prof.save()
                user.save()
            else:
                form.add_error('email', 'Your institution has not registered your email domain.')

            if form.is_valid():
                context = { 'user': user }
                return render(request, 'users/registration_successful.html', context)

    context = { 'form': form }
    return render(request, 'users/register.html', context)
#endregion


def choose_app_view(request):
    return render(request, 'users/choose_app_view.html', {})

django/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <title>PC - {% block page_title %}{% endblock page_title %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="student, professor, rate, team, project, review, peer, group">
    <meta name="author" content="ProjectConnect">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index follow">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&family=Bellefair&family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    {% block more_links %}{% endblock more_links %}

    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

    {{ hotjar_script|safe }}

    <style>
        {% block page_style %}{% endblock page_style %}
    </style>
</head>

<body class="bg-white">
    <div class="page-container">
        <div class="content-wrap">
            <nav class="navbar navbar-expand-lg navbar-light bg-white shadow"
                    style="border-top: 1px solid hsl( var(--clr-brand-blue) ); border-bottom: 3px solid hsl( var(--clr-brand-blue) );">
                    <div class="navbar-brand">
                        <a href="{% url 'public_pages:index' %}"><img class="navbar-img" src="{% static 'img/projectconnect-logo-lg.png' %}"
                            alt="ProjectConnect logo featuring prominent C-shape with user icons" width="10%" style="margin-right: 1rem;"></a>
                    </div>

                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive" aria-controls="navbarResponsive"
                        aria-expanded="false", aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav mr-auto" style="text-align: center;">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'public_pages:index' %}" alt="Link to homepage">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                        <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                                    </svg>
                                    <br>Home<span class="sr-only">(current)</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            {% block content %}

            {% endblock content %}
        </div>
    </div>

    <footer class="shadow text-right">
        <div>
            <a class="bttn-outline-brand-blue" href="{% url 'public_pages:about' %}" alt="Link to About Us page" style="float: left; margin-top: 1em;">About Us</a>
            <span class="fs-100 text-right"><a href="#" style="text-decoration: none; color: #000;"> &copy;</a>
                &nbsp;ProjectConnect, Inc. 2022</span>
        </div>
        <div>
            <img class="navbar-img" id="hide-on-small-phone" src="{% static 'img/projectconnect-logo-footer.png' %}"
                alt="ProjectConnect logo featuring prominent C-shape with user icons" style="float: right;">
        </div>
    </footer>
</body>

</html>

django/templates/users/choose_app_view.html
{% extends './base.html' %}

{% block page_title %}Choose Application View{% endblock %}

{% block content %}
<br>
<div class="container-sm flow">
    <div class="lightly-pad-container shadow text-break text-center">
        <h1 class="ff-sans-bolder">Continue as Professor or Student?</h1>
        <p>
            Your account has both a professor profile and a student profile.<br>
            Choose which one you would like to use in this browser session.
        </p>

        <div class="form-container">
            <div class="row">
                <div class="col">
                    <h3 style="margin-bottom: 2rem;">Professor View</h3>
                    <a href="{% url 'professors:index' %}">
                        <button class="bttn-brand-blue">Continue as a professor</button>
                    </a>
                </div>
                <div class="col">
                    <h3 style="margin-bottom: 2rem;">Student View</h3>
                    <a href="{% url 'students:index' %}">
                        <button class="bttn-brand-blue">Continue as a student</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

django/templates/users/login.html
{% extends './base.html' %}

{% block page_title %}Login{% endblock page_title %}

{% block page_style %}
span.asteriskField { display: none; }
{% endblock page_style %}

{% block content %}
{% load crispy_forms_tags %}
<div class="login-container shadow">
    <h2 class="text-center">Sign in to continue</h2>
    <br>
    {% for message in messages %}
    <div class="alert alert-warning">
        <a class="close" href="#" data-dismiss="alert">×</a>
           {{ message }}
    </div>
    {% endfor %}
    <form action="{% url 'users:login' %}" method='post'>
        {% crispy form %}
        <div class="d-flex pad-container justify-content-center">
            <button class="bttn-brand-blue" type="submit"
                style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                Log In
            </button>
        </div>
    </form>
    <br>
    Forgot your password?&nbsp;<a href="{% url 'users:reset_password' %}">Reset it here</a>.
</div>
{% endblock content %}

django/templates/users/register.html
{% extends './base.html' %}

{% block page_title %}Login{% endblock page_title %}

{% block content %}
{% load crispy_forms_tags %}
<br>
<div class="container-sm flow">
    <div class="lightly-pad-container shadow text-break text-center">
        <h1 class="ff-sans-bolder">Sign up for a free account</h1>
        <div class="form-container">
            <form action="{% url 'users:register' %}" method='post'>
                {% crispy form %}
                <div class="form-row">
                    <div class="col-25">
                       <label class="col-form-label requiredField" for="id_tos">Terms of Service*</label>
                   </div>
                    <div class="col-75 tos-box">
                        <input id="id_tos" type="checkbox" name="tos" required="" aria-labelledby="tos-description">
                        <span id="tos-description">I agree to these <a href="#">Terms and Conditions</a>.</span>
                   </div>
               </div>
                <div class="form-row">
                    <div class="col-25">
                        &nbsp;
                   </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-brand-blue" type="submit"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Register
                        </button>
                   </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-danger" onclick="javascript:window.location.replace('/')"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Cancel
                        </button>
                   </div>
               </div>
            </form>
       </div>
   </div>
</div>
{% endblock content %}

django/templates/users/registration_successful.html
{% extends './base.html' %}

{% block page_title %}Registration Successful{% endblock %}

{% block content %}
<br>
<div class="container-sm flow">
    <div class="lightly-pad-container shadow text-break text-center">
        <h1 class="ff-sans-bolder">Registration Successful</h1>
        <p>
            Your account has been registered.
        </p>

        <div class="form-container">
            <div class="d-flex justify-content-center card-row">
                <div class="col card-thin-border">
                    <h4 class="text-center">Your Account</h4>
                    Name:     {{ user.first_name }} {{ user.last_name }}<br>
                    Email:    {{ user.email }}
                </div>
                <div class="col card-thin-border">
                    <h4 class="text-center">Login</h4>
                    <a class="text-center" href="{% url 'users:login' %}" style="margin-top: 1rem;">
                        <button class="bttn-brand-blue">Go to Login</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}