django/projectconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public_pages.urls')),
    path('professors/', include('professors.urls')),
    path('students/', include('students.urls')),
    path('users/', include('users.urls')),
]

django/public_pages/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as users_views
from . import views

app_name = 'public_pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('about/<str:section>', views.about_section, name='about_section'),
    path('hotjar/', views.hotjar, name='hotjar'),
    # In addition to users/login being valid URL, I'm
    # making login and accounts/login valid URLs for the
    # login page too.
    path('accounts/login/', users_views.login_view, name='login'),
    path('login/', users_views.login_view, name='login'),
]


handler404 = views.handle_404

django/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

django/users/urls.py
from django.urls import path, reverse_lazy
from django.urls import path, include
from django.contrib.auth import login, views as auth_views
from . import views
from .forms import CustomSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('choose_app_view/', views.choose_app_view, name='choose_app_view'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('route_user/', views.route_user, name='route_user'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/password_reset/reset_password_email.html',
			email_template_name='users/password_reset/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_sent'),
		), name='reset_password'),

	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/password_reset/reset_password_sent.html'), name='password_reset_sent'),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            form_class=CustomSetPasswordForm,
			template_name='users/password_reset/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='password_reset_confirm'),

	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/password_reset/reset_password_complete.html'), name='password_reset_complete')
]

django/students/models.py
from email.policy import default
from django.db import models
from institutions.models import Institution
from users.models import EmailAuthUser
from functools import partial
from os import path

'''
I've already added the profile_image and profile_image_file_name
fields to the Student model and got the upload models and the Student
models migrated. It's up to you to implement it by writing the views
code, the form, the urls routing, and the HTML template.
'''

def _update_filename(instance, filename, path):
    return path.join(path, filename)

def upload_to(path):
    return partial(_update_filename, path=path)

class S3Upload(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)

class S3StudentUpload(S3Upload):
    _upload_to='img/students/profile_icons'
    file = models.FileField(upload_to=(_upload_to))

class StudentRole(models.Model):
    text = models.CharField(max_length=50)

class StudentSkill(models.Model):
    text = models.CharField(max_length=50)

class Student(models.Model):
    pronouns    = models.CharField(max_length=100)
    bio         = models.CharField(max_length=300)
    grade_level = models.CharField(max_length=9)
    major       = models.CharField(max_length=69)
    minor       = models.CharField(max_length=69)

    avg_rating  = models.FloatField(default=0)
    avg_participation     = models.FloatField(default=0)
    avg_contribution      = models.FloatField(default=0)
    avg_work_timeliness   = models.FloatField(default=0)
    avg_work_quality      = models.FloatField(default=0)
    avg_cooperativeness   = models.FloatField(default=0)
    avg_communicativeness = models.FloatField(default=0)

    profile_icon           = models.FileField()
    profile_icon_file_name = models.CharField(max_length=30, default='default_profile_icon.png')

    institution = models.ForeignKey(Institution, on_delete=models.DO_NOTHING)
    roles = models.ManyToManyField(StudentRole)
    skills = models.ManyToManyField(StudentSkill)
    user = models.ForeignKey(EmailAuthUser, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"\nid:        {self.id}\n"
            f"institution: {self.institution}\n"
            f"profile icon path:      '{S3StudentUpload._upload_to}'\n"
            f"profile icon file name: '{self.profile_icon_file_name}'"
        )

django/students/forms.py
from cProfile import label
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Column
from .models import *

class SelectFieldChoices:
    # Create tuples for select option here.
    # The first string in each row is the
    # actual value to store in the database.
    # The second string is what the user sees.

    GRADE_LEVEL_CHOICES = (
        ('Freshman', 'Freshman'),
        ('Sophomore', 'Sophomore'),
        ('Junior', 'Junior'),
        ('Senior', 'Senior'),
        ('Other', 'Other')
    )

class StudentForm(forms.ModelForm):

    profile_icon = forms.FileField(
        label='Profile icon',
        required=False,
        widget=forms.FileInput(attrs={
            'multiple': False,
            'accept': 'image/*'
        })
    )

    grade_level = forms.CharField(
        label='Choose grade level',
        required=False,
        widget=forms.Select(choices=SelectFieldChoices.GRADE_LEVEL_CHOICES)
    )

    major = forms.CharField(
        label="What's your major?",
        required=False,
    )

    minor = forms.CharField(
        label="What's your minor, if any?",
        required=False,
    )

    pronouns = forms.CharField(
        label='Personal pronouns',
        required=False,
    )

    bio = forms.CharField(
        label='Bio',
        required=False,
        widget=forms.Textarea(attrs={
            'rows': '3',
            'cols': '40',
            'placeholder': 'Tell students about yourself in 300 characters.'
        })
    )


    class Meta:
        model = Student
        fields = [
            'profile_icon', 'grade_level', 'major',
            'minor', 'pronouns', 'bio',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-25 fs-400 ff-sans-normal'
        self.helper.field_class='col-75'
        self.helper.form_tag = False

django/students/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from students.models import *
from students.forms import *

from users.decorators import allowed_users

from datetime import datetime as dt, timedelta

@login_required
@allowed_users(allowed_groups=['students'])
def index(request):
    student = Student.objects.get(user=request.user)
    context = {
        'student': student,
        'students': Student.objects.filter(institution=student.institution)
    }
    return render(request, 'students/index.html', context)

@login_required
@allowed_users(allowed_groups=['students'])
def edit_profile(request):
    student = Student.objects.get(user=request.user) 
    if request.method != 'POST': 
        form = StudentForm(instance=student)
    else:                                       
        form = StudentForm(instance=student, data=request.POST) 
        if form.is_valid():
            print(form.fields['grade_level'])
            form.save()
            print(request.POST['grade_level'])
            if len(request.FILES) != 0:
                if 'profile_icon' in request.FILES.keys():
                    image = request.FILES['profile_icon']
                    image.name = 'profile-icon-' + str(student.id) + path.splitext(image.name)[1]
                    u = S3StudentUpload(file=image)
                    u.save()
                    student.profile_icon_file_name=image.name
                    student.save()

            return HttpResponseRedirect(reverse('students:index'))

    context = { 'student': student, 'form': form }
    return render(request, 'students/edit_profile_form.html', context)


django/templates/students/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <title>PC Student - {% block page_title %}{% endblock page_title %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="student, professor, rate, team, project, review, peer, group">
    <meta name="author" content="ProjectConnect">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index follow">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&family=Bellefair&family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    {% block more_links %}{% endblock more_links %}

    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

    {{ hotjar_script|safe }}

    <style>
        #navbar-brand { white-space: nowrap; }
        .navbar-img { display: inline-block; }
        {% block page_style %}{% endblock page_style %}
    </style>
</head>

<body class="bg-white">
    <div class="page-container">
        <div class="content-wrap">
            <nav class="navbar navbar-expand-lg navbar-light bg-white shadow"
                style="border-top: 1px solid hsl( var(--clr-brand-blue) ); border-bottom: 3px solid hsl( var(--clr-brand-blue) );">
                <div class="navbar-brand">
                    <a href="{% url 'students:index' %}"><img class="navbar-img" src="{% static 'img/projectconnect-logo-lg.png' %}"
                        alt="ProjectConnect logo featuring prominent C-shape with user icons" width="10%" style="margin-right: 1rem;"></a>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive"
                    aria-expanded="false", aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto" style="text-align: center;">
                        <li class="nav-item">
                            <a class="nav-link active" href="index.html" alt="Link to homepage">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                                </svg>
                                <br>Home<span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" alt="Link to friends page">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                    <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                                </svg>
                                <br>Friends
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" alt="Link to projects page">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-archive-fill" viewBox="0 0 16 16">
                                    <path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                                </svg>
                                <br>Projects
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-dropbttn nav-dropbttn" onclick="toggleDropdown('profile-dropdown-content')" alt="Link to profile page">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                </svg>
                                <br>Profile
                            </a>
                            <div class="profile-dropdown-content nav-dropdown-content" id="profile-dropdown-content">
                                <div class="row card-row">
                                    <div class="col">
                                        {% with 'img/students/profile_icons/'|add:student.profile_icon_file_name as profile_icon_static %}
                                        <img class="border-brand-blue" style="border-radius: 50%;"
                                            src="{% static profile_icon_static %}" alt="Profile icon">
                                        {% endwith %}
                                    </div>
                                    <div class="col">
                                        {{ user.first_name }} {{ user.last_name }}
                                    </div>
                                </div>
                                <p>
                                    {% if not student.major == '' %}
                                    🎓 {{ student.major }}
                                    {% endif %}
                                    {% if not student.grade_level == '' %}
                                    · {{ student.grade_level }}
                                    {% endif %}
                                </p>
                                <a href="{% url 'students:edit_profile' %}">Edit profile</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-dropbttn" onclick="toggleDropdown('settings-dropdown-content')" alt="Link to open Settings menu">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                                </svg>
                                <br>Settings
                            </a>
                            <div class="nav-dropdown-content" id="settings-dropdown-content">
                                <div class="row card-row">
                                    <div class="col fs-300 text-dark"><a href="{% url 'users:logout' %}">Log out</a></div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <footer class="shadow text-right">
        <div>
            <a class="bttn-outline-brand-blue" href="{% url 'public_pages:about' %}" alt="Link to About Us page" style="float: left; margin-top: 1em;">About Us</a>
            <span class="fs-100 text-right"><a href="#" style="text-decoration: none; color: #000;"> &copy;</a>
                &nbsp;ProjectConnect, Inc. 2022</span>
        </div>
        <div>
            <img class="navbar-img" id="hide-on-small-phone" src="{% static 'img/projectconnect-logo-footer.png' %}"
                alt="ProjectConnect logo featuring prominent C-shape with user icons" style="float: right;">
        </div>
    </footer>

    <script>
        function closeDropdowns() {
            let dropdowns = document.getElementsByClassName("nav-dropdown-content");
            let i;
            for (i = 0; i < dropdowns.length; i++) {
              let openDropdown = dropdowns[i];
              console.log(i);
              if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
              }
            }
        }

        function toggleDropdown(id) {
            closeDropdowns(); // First close dropdowns that could already be open.
            document.getElementById(id).classList.toggle("show");
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.nav-dropbttn')) {
                closeDropdowns();
            }
        }
    </script>
    {% block body_scripts %}{% endblock body_scripts %}
</body>

</html>

django/templates/students/edit_profile_form.html
{% extends './base.html' %}

{% block page_title %}Edit Student Profile{% endblock page_title %}

{% block more_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock more_links %}

{% block content %}
{% load crispy_forms_tags %}

<br>
<div class="container-sm flow">
    <div class="lightly-pad-container shadow text-break text-center">
        <h2 class="ff-sans-bolder">Edit Student Profile</h2>
        <div class="form-container">
            <div class="row">
                <div class="col-25"></div>
                <div class="col-75">
                    <div class="col-25">
                    </div>
                    {% with 'img/students/profile_icons/'|add:student.profile_icon_file_name as profile_icon_static %}
                    <img id="profile-icon" width="150" src="{% static profile_icon_static %}" alt="Student's profile icon" style="border-radius: 50%;">
                    {% endwith %}
                </div>
            </div>
            <br>
            <form action="{% url 'students:edit_profile' %}" method='post' enctype='multipart/form-data'>
                {% crispy form %}
                <div class="form-row">
                    <div class="col-25">
                        &nbsp;
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-brand-blue" type="submit"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Save
                        </button>
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-danger" onclick="javascript:window.location.replace('/students')"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Cancel
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block body_scripts %}
<script>
    $("#id_profile_icon").on("change", function() {
        let input = this;
        let filename = $(this).val();
        let ext = filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();
        if (input.files && input.files[0] && (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg"))
        {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#profile-icon').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    });
</script>
{% endblock body_scripts %}

django/templates/students/index.html
{% extends './base.html' %}
{% load static %}

{% block page_title %}Home{% endblock page_title %}

{% block page_style %}
    #navbar-brand { white-space: nowrap; }
    .bttn, .navbar-img { display: inline-block; }

    ul.list li {
        margin-top: 20px;
    }

    #disp-block-when-small {
        display: inline;
    }

    @media only screen
    and (max-width: 608px) {
        #disp-block-when-small {
            display: block;
            margin-top: 1em;
        }
    }
{% endblock page_style %}

{% block content %}
<div class="center lightly-pad-container" id="student-search-list" style="align-items: right; text-align: right;">
    <span class="text-left mr-5">Welcome {{ user.first_name }}!</span>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    <input type="text" class="search" placeholder="Name, grade level, rating" style="border-radius: 2px; vertical-align: middle;">
    <div class="fs-200" id="disp-block-when-small">
        <a style="margin-left: 14px;">
            <button class="sort btn btn-outline-primary" id="student-name-sort" data-sort="student-name">
                <i class="bi bi-sort-alpha-up" id="student-name-sort-icon"></i>
            </button>
            Sort A-Z
        </a>
        <a style="margin-left: 14px;">
            <button class="sort btn btn-outline-primary" id="student-rating-sort" data-sort="student-rating">
                <i class="bi bi-sort-numeric-up" id="student-rating-sort-icon"></i>
            </button>
            Sort rating
        </a>
    </div>
    <div class="center">
        <ul class="list">
            {% for student in students %}
            <li>
                <div class="row bg-white border-brand-blue">
                    <div class="col-xs">
                        {% with 'img/students/profile_icons/'|add:student.profile_icon_file_name as profile_icon_static %}
                        <img class="border-brand-blue" alt="{{ student.user.first_name }} {{ student.user.last_name }}'s profile" src="{% static profile_icon_static %}" style="border-radius: 50%;" width="100px">
                        {% endwith %}
                    </div>
                    <div class="col-md">
                        <p class="fs-600">
                            <a class="student-name">{{ student.user.first_name }}  {{ student.user.last_name }}</a>
                        </p>
                        <p>
                            {% if not student.grade_level == '' %}
                            🪜&nbsp;<a class="student-gradelevel">{{ student.grade_level }}</a>&nbsp;
                            {% endif %}
                            {% if not student.major == '' %}
                            🎓&nbsp;<a class="student-major">{{ student.major }}</a>
                            {% endif %}
                            <br>
                        </p>
                        {% if not student.minor == '' %}
                        <p>
                            🤓&nbsp;<a class="student-minor">Minor: {{ student.minor }}</a>
                        </p>
                        {% endif %}
                        <a class="student-rating">
                        {% if not student.avg_rating == 0 %}
                            {% if student.avg_rating < 2 %}
                            ★
                            {% elif student.avg_rating < 3 %}
                            ★★
                            {% elif student.avg_rating < 4 %}
                            ★★★
                            {% elif student.avg_rating < 5 %}
                            ★★★★
                            {% else %}
                            ★★★★★
                            {% endif %}
                        {% endif %}
                        </a>
                    </div>
                    <div class="col-md center">
                        <br>
                        <a class="bttn-outline-brand-blue" href="#">Connect</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<script src="{% static 'js/list.js' %}"></script>
<script src="{% static 'js/student-search.js' %}"></script>
<script>
    $(document).ready(function() {
        let studentRatingSort = document.getElementById('student-rating-sort');
        let studentNameSort = document.getElementById('student-name-sort');
        let studentRatingSortIcon = document.getElementById('student-rating-sort-icon');
        let studentNameSortIcon = document.getElementById('student-name-sort-icon');

        let sortNumericUp_Displayed = true;
        let sortNameUp_Displayed = true;

        studentRatingSort.addEventListener('click', () => {
            if (sortNumericUp_Displayed) {
                studentRatingSortIcon.classList.remove("bi-sort-numeric-up");
                studentRatingSortIcon.classList.add("bi-sort-numeric-down-alt");
            }
            else {
                studentRatingSortIcon.classList.remove("bi-sort-numeric-down-alt");
                studentRatingSortIcon.classList.add("bi-sort-numeric-up");
            }
            sortNumericUp_Displayed = !sortNumericUp_Displayed;
        });

        studentNameSort.addEventListener('click', () => {
            if (sortNameUp_Displayed) {
                studentNameSortIcon.classList.remove("bi-sort-alpha-up");
                studentNameSortIcon.classList.add("bi-sort-alpha-down-alt");
            }
            else {
                studentNameSortIcon.classList.remove("bi-sort-alpha-down-alt");
                studentNameSortIcon.classList.add("bi-sort-alpha-up");
            }
            sortNameUp_Displayed = !sortNameUp_Displayed;
        });
    });
</script>
{% endblock content %}