django/projectconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public_pages.urls')),
    path('professors/', include('professors.urls')),
    path('students/', include('students.urls')),
    path('users/', include('users.urls')),
]

django/public_pages/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as users_views
from . import views

app_name = 'public_pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('about/<str:section>', views.about_section, name='about_section'),
    path('hotjar/', views.hotjar, name='hotjar'),
    # In addition to users/login being valid URL, I'm
    # making login and accounts/login valid URLs for the
    # login page too.
    path('accounts/login/', users_views.login_view, name='login'),
    path('login/', users_views.login_view, name='login'),
]


handler404 = views.handle_404

django/users/urls.py
from django.urls import path, reverse_lazy
from django.urls import path, include
from django.contrib.auth import login, views as auth_views
from . import views
from .forms import CustomSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('choose_app_view/', views.choose_app_view, name='choose_app_view'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('route_user/', views.route_user, name='route_user'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/password_reset/reset_password_email.html',
			email_template_name='users/password_reset/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_sent'),
		), name='reset_password'),

	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/password_reset/reset_password_sent.html'), name='password_reset_sent'),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            form_class=CustomSetPasswordForm,
			template_name='users/password_reset/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='password_reset_confirm'),

	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/password_reset/reset_password_complete.html'), name='password_reset_complete')
]

django/public_pages/models.py
from django.db import models

class HotJar(models.Model):
    hotjar_script = models.CharField(max_length=2200)

django/public_pages/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from public_pages.models import HotJar

class HotJarForm(forms.ModelForm):
    hotjar_script = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows': '4',
            'cols': '40',
            'placeholder': ('Paste your HotJar script here and'
                            ' it will be automatically injected on each page.')
        })
    )

    class Meta:
        model = HotJar
        fields = [ 'hotjar_script' ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-25 fs-400 ff-sans-normal'
        self.helper.field_class='col-75'
        self.helper.form_tag = False

django/public_pages/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime as dt, timedelta
from .models import HotJar
from .forms import HotJarForm
from django.contrib.auth.decorators import login_required


def handle_404(request, exception):
    return render(request, '404.html', context={})

def index(request):
    return render(request, 'public_pages/index.html', context={})

def about(request):
    return render(request, 'public_pages/about.html', context={})

def about_section(request, section):
    """Template script will go to the section with the ID that matches the section arg."""
    return render(request, 'public_pages/about.html',
                    context={ 'goto_section': section })

@login_required
def hotjar(request):
    hotjar = HotJar.objects.get(id=1)
    if not request.method == 'POST':
        form = HotJarForm(instance=hotjar)
    else:
        form = HotJarForm(instance=hotjar, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('public_pages:index'))

    return render(request, 'public_pages/hotjar.html', context={ 'form': form })

django/templates/public_pages/about.html
{% extends './base.html' %}

{% block page_title %}About{% endblock page_title %}
{% block content %}
<div class="lightly-pad-container bg-brand-blue text-white text-break">
    <div class="center">
        <h1 class="ff-sans-bolder text-center textshadow">About Us</h1>
    </div>
</div>

<div class="flow container">
    <div class="row card-row">
        <div class="col-sm card-thin-border" id="students">
            <h3 class="text-center">Students</h3>
            <p class="card-text">
                Picking the right collaborators for a project can feel like a shot in
                the dark, especially if you haven't met many of your peers. You need to
                know who's responsible, who communicates well, or who can lead effectively.
                ProjectConnect aims at taking the guesswork out of choosing your teammates
                by showing you ratings of other students in your college and in your classes.
                By providing an easy way of searching through to find potential teammates, you
                can take some stress away of finding the perfect team.

                {% load static %}
                <img src="{% static 'img/about/Student.png' %}" scale="100%">
            </p>
        </div>
        <div class="col-xs"><p>&emsp;&emsp;</p></div>
        <div class="col-sm card-thin-border" id="professors">
            <h3 class="text-center">Professors</h3>
            <p class="card-text">
                For class settings where the professor assigns teams,
                ProjectConnect offers a great way to get insight into which students
                will work well together, what problems students are having with their
                peers, and moderate students' evaluations. By providing ways for professors
                to easily create courses and keep sections uniquely identified, all the while
                allowing them to create specific projects within each course to keep track of
                progress.

                {% load static %}
                <img src="{% static 'img/about/Professors.PNG' %}">
            </p>
        </div>
    </div>
</div>

{% if 'goto_section' %}
<script> window.location.hash = '#{{ goto_section }}'; </script>
{% endif %}
{% endblock content %}

django/templates/public_pages/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <title>PC - {% block page_title %}{% endblock page_title %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="student, professor, rate, team, project, review, peer, group">
    <meta name="author" content="ProjectConnect">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index follow">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&family=Bellefair&family=Barlow:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    {% block more_links %}{% endblock more_links %}

    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

    {{ hotjar_script|safe }}

    <style>
        #navbar-brand { white-space: nowrap; }
        .navbar-img { display: inline-block; }
        {% block page_style %}{% endblock page_style %}
    </style>
</head>

<body class="bg-white">
    <div class="page-container">
        <div class="content-wrap" {% block cw_style %}{% endblock cw_style%}>
            <nav class="navbar navbar-expand-lg navbar-light bg-white shadow"
                style="border-top: 1px solid hsl( var(--clr-brand-blue) ); border-bottom: 3px solid hsl( var(--clr-brand-blue) );">
                <div class="navbar-brand">
                    <a href="{% url 'public_pages:index' %}"><img class="navbar-img" src="{% static 'img/projectconnect-logo-lg.png' %}"
                        alt="ProjectConnect logo featuring prominent C-shape with user icons" width="10%" style="margin-right: 1rem;"></a>
                    <a class="bttn-brand-blue" href="{% url 'users:register' %}" alt="Link to register page" style="margin-right: 1rem;">Register</a>
                    <a class="bttn-outline-brand-blue" href="{% url 'public_pages:login' %}" alt="Link to login page">Log In</a>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive"
                    aria-expanded="false", aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto" style="text-align: center;">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'public_pages:index' %}" alt="Link to homepage">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                                </svg>
                                <br>Home<span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'public_pages:about' %}" alt="Link to projects page">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1.6em" height="1.6em" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                                  </svg>
                                <br>About
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            {% block content %}

            {% endblock content %}
        </div>
    </div>

    <footer class="shadow text-right">
        <div>
            <a class="bttn-outline-brand-blue" href="{% url 'public_pages:about' %}" alt="Link to About Us page" style="float: left; margin-top: 1em;">About Us</a>
            <span class="fs-100 text-right"><a href="#" style="text-decoration: none; color: #000;"> &copy;</a>
                &nbsp;ProjectConnect, Inc. 2022</span>
        </div>
        <div>
            <img class="navbar-img" id="hide-on-small-phone" src="{% static 'img/projectconnect-logo-footer.png' %}"
                alt="ProjectConnect logo featuring prominent C-shape with user icons" style="float: right;">
        </div>
    </footer>
</body>

</html>

django/templates/public_pages/hotjar.html
{% extends './base.html' %}

{% block page_title %}HotJar Script{% endblock page_title %}

{% load static %}

{% block more_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock more_links %}

{% block content %}
{% load crispy_forms_tags %}
<br>
<div class="container-sm flow">
    <div class="lightly-pad-container shadow text-break text-center">
        <h2 class="ff-sans-bolder">Insert Hotjar Script</h2>
        <div class="form-container">
            <div class="row">
                <div class="col-25"></div>
                <div class="col-75">
                    <div class="col-25">
                    </div>
                    <img id="profile-icon" width="150" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpjr-kAOx73jB0EzC06BANDrdhss3C1d6z8T811vdiWiCNosLu5wg1POkgFZgVAO5p5bY&usqp=CAU" alt="HotJar icon" style="border-radius: 10%;">
                </div>
            </div>
            <br>
            <form action="{% url 'public_pages:hotjar' %}" method='post' enctype='multipart/form-data'>
                {% crispy form %}
                <div class="form-row">
                    <div class="col-25">
                        &nbsp;
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-brand-blue" type="submit"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Save
                        </button>
                    </div>
                    <div class="col-25" style="text-align: left;">
                        <button class="bttn-danger" onclick="javascript:window.location.replace('/')"
                            style="margin-top: 1em; padding-left: 10%; padding-right: 10%;">
                            Cancel
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

django/templates/public_pages/index.html
{% extends './base.html' %}

{% block page_title %}Home{% endblock page_title %}

{% load static %}
{% block cw_style %}
style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.5)), url('{% static 'img/home/teamwork.jpg' %}');"
{% endblock cw_style %}

{% block content %}
<div class="lightly-pad-container bg-brand-blue text-white text-break">
    <h1 class="ff-sans-bolder text-center textshadow">Welcome to ProjectConnect!</h1>
</div>

<div class="flow container">
    <div class="row card-row">
        <div class="col-sm card">
            <h3 class="text-center">For Students</h3>
            <p class="card-text">
                Picking the right collaborators for a project can feel like a shot in
                the dark, especially if you haven't met many of your peers. You need to
                know who's responsible, who communicates well, or who can lead effectively.
                ProjectConnect aims at taking the guesswork out of choosing your teammates
                by showing you ratings of other students in your college and in your classes.
                <br><br>
                Ratings are based off of peer evaluations from past projects, so as more
                projects are completed, you get a better idea of your peers' strengths and
                weaknesses. All of this makes it easier on you, the student, to find others
                who can be a good fit on your next team.
                <br><br>
                <a href="{% url 'public_pages:about_section' section='students' %}"><button class="bttn-brand-blue" style="width: 100%;">Find out more</button></a>
            </p>
        </div>
        <div class="col-xs"><p>&emsp;&emsp;</p></div>
        <div class="col-sm card">
            <h3 class="text-center">For Professors</h3>
            <p class="card-text">
                Class project grades often depend in part on peer evaluations. Creating,
                distributing, and keeping track of all the evaluations your students
                complete across courses and sections can be a headache. ProjectConnect
                streamlines the your ability to distribute and track peer evaluations.
                You can set them to be sent to your students on a per-project basis at
                a precise time and view who has completed them in each class.
                <br><br>
                What's more? For class settings where the professor assigns teams,
                ProjectConnect offers a great way to get insight into which students
                will work well together, what problems students are having with their
                peers, and moderate students' evaluations.
                <br><br>
                <a href="{% url 'public_pages:about_section' section='professors' %}"><button class="bttn-brand-blue" style="width: 100%;">Find out more</button></a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}